{% set name = "pyspeckle" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspeckle-{{ version }}.tar.gz
  sha256: edec79a80636f1a60d3906f1d6711550f6f54a268620c33415b5617bb5a55a88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - matplotlib-base
    - numpy
    - scipy
    - python >={{ python_min }}

test:
  imports:
    - pyspeckle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scottprahl/pyspeckle.git
  summary: |
    A collection of routines to generatess and analyze laser speckle.  This is a 
    python port of SimSpeckle Matlab routines described in Duncan & Kirkpatrick, 
    "Algorithms for simulation of speckle (laser and otherwise)," in SPIE Vol. 
    6855 (2008).

    This implementation contains code for 1D exponential and gaussian speckle,
    2D speckle algorithms, and 3D speckle generation.

  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://pyspeckle2.readthedocs.io/
  dev_url: https://github.com/scottprahl/pyspeckle

extra:
  recipe-maintainers:
    - scottprahl
